### ISSUE TITLE
book-nobook prediction

### ISSUE THREAD

**Issue by boliangz** [thu-spmi/damd-multiwoz#3]
Thanks for sharing the code. I have one question about how the system predicts fail_book (book-nobook).

When the user sends a booking request, such as "Can you book for 1 at 20:00 on Tuesday ?", the system may either reply "Booking was successful..." or "I 'm sorry , it looks like they are both booked...". My question is what information the system depends on in order to make a correct prediction? Does it have access to the ground truth act Booking-NoBook?

**Comment by 594zyc** [comment]
Hi, 

Thanks for your interest. 

Since the information whether booking is available is not provided in MultiWOZ, we use the ground-truth database pointer (based on the ground truth system actions) in our experiments. The model still needs to predict whether to choose the action of returning a booking results, but the booking availability cannot be inferred without given the ground-truth to our knowledge.

**Comment by boliangz** [comment]
Thanks for the information.
