### ISSUE TITLE
Multiwoz evaluation

### ISSUE THREAD

**Issue by unbiarirang** [thu-spmi/damd-multiwoz#4]
Hi, thank you for sharing the code!
I appreciate your work and I have a question. 

The original MultiWoz evaluate.py calculates the INFORM score by checking if the first offered venue is correct or not.
`elif len(venue_offered[domain]) > 0 and venue_offered[domain][0] in goal_venues: match += 1`
However your evaluation code is checking if there's an overlap between offered venues and goal venues.
`elif len(venue_offered[domain]) > 0 and len(set(venue_offered[domain])& set(goal_venues))>0: match += 1`
Doesn't it lead to a higher score than the original evaluation code?

**Comment by 594zyc** [comment]
Hi, 

We use this checking criterion because it can return a deterministic score for the same set of offered venues under different runs. In the original setting, the match score depends on the order of the venues which is random. Because any venue that meets the search constraint can be the "first offered venue", such randomness does not make sense. Our setting corresponds to the most optimistic results the original evaluation setting can obtain, when one of the overlaps is always returned as the first offered venue. In other words, our criterion is no better than the best score the original criterion can get. I remember that the largest gain of using our criterion is less than 0.5 on the match rate (not sure since this was done a long time ago), which may suggest that the difference is minimal. 

Besides, these two criteria both have a problem. The offered venue is still possible to match the user's goal even if the system's belief in the user goals (informable slot values) does not exactly match the real user goal. Such lucky successes should be avoided, which can be done by comparing whether the set of offered venues is the same as the goal venues. 

Hope this can help.

**Comment by Tomiinek** [comment]
Hello guys,

I am currently going through evaluation scripts of several recent systems so I just would like to mention a few things here. @594zyc is right that this is an optimistic evaluation and that both criteria have a problem. I think that checking whether the set of offered venues is a non-empty subset of the set of venues complying the dialog goal makes more sense. It can be seen in [MarCo](https://github.com/InitialBug/MarCo-Dialog/blob/2b9ff5929e4b924ec130cd7ceeeda9991186ab99/evaluator.py#L184) and [HDSA](https://github.com/wenhuchen/HDSA-Dialog/blob/88e2604adb5dc38ae32205410b15b2ac39116ecd/evaluator.py#L181).

Also note that DAMD uses reduced database queries when a venue name is in search constraints (see [these lines](https://github.com/thu-spmi/damd-multiwoz/blob/9b0456d7e590fb5de77ec81e967e8010487eeb56/db_ops.py#L142-L150)). I think that this also overestimates the actual system's performance, because previous ground-truth responses (including ground-truth names) are used as the context during evaluation. And so the right venue name can be copied into the predicted dialog state in later turns and all the DST done up to this point (which might contradict the dialog goal) is in fact discarded.

If I apply both changes, I get about 20% lower Inform rate.

All the best :slightly_smiling_face:

**Comment by unbiarirang** [comment]
Hi, thank you both for answering!

As @Tomiinek said, I feel checking whether the set of offered venues is a non-empty subset of the set of venues makes sense.
However, for venue name constraints, I think the original evaluation code has the same logic [here](https://github.com/budzianowski/multiwoz/blob/849d62b99f824eb4cf4857c1986d9e7de4fb8e31/evaluate.py#L272). So I guess it will be okay.

**Comment by Tomiinek** [comment]
> However, for venue name constraints, I think the original evaluation code has the same logic here. So I guess it will be okay.

No, I am afraid it is not. The logic you linked accepts a dialog as matching if the name of a venue is in the dialog goal, i.e. the crowd worker was instructed to mention it during the data collection. So the name is probably somewhere in **user utterances**.

However, the name constraint in case of DAMD is related to **system responses** only. If the user was not instructed to mention the name, we should rely just on the model predictions during evaluation. But the problem is that the predictions can be ignored later in the dialog if the reduced set of constraints is used for querying the database.

:thought_balloon:  The Inform Rate assesses if for each domain contained in the dialogue, the last mentioned entity (venue name or train id) for that domain matches the requirements in the user's goal.

**Comment by unbiarirang** [comment]
> If the user was not instructed to mention the name, we should rely just on the model predictions during evaluation.

If the user wasn't instructed to mention the name, I thought the constraint would not have the name, so we just rely on the model predictions. Is it wrong to think this way?

**Comment by Tomiinek** [comment]
The evaluation uses ground-truth utterances in the context, because there is no user simulator.

Let me think of an example:

- The user is looking for a `pricerange: cheap, food: Chinese` restaurant. She is not instructed to mention a name, she just want to find out a cheap Chinese restaurant and its postcode. 
- The model at some point makes a mistake predicting a state `pricerange: moderate, food: Chinese`, and informs the user with `"I have [name_restaraunt] matching your request, would you like me to book it for you?"`. Because the `[name_restaurant]` was mentioned, the set of offerend venues is updated. This set isn't a subset of the set of goal venues, so the dialog is not matching at this point.
- And now comes the problem. The next turn is generated using the ground-truth context, so it can contain something similar to  `"USR: Could you find me a cheap Chinese restaurant? SYS: Sure, I have Golden dragon matching your request, do you like it?"` where `Golden dragon` is cheap and serves Chinese food. If the user now asks for example for the post code, i.e. `"Yes I do, give me its postcode please."`, the model can predict a partially incorrect state such as `pricerange: moderate, food: Chinese, name: Golden dragon` and inform the user with a utterance such as `"[name_restaurant] postcode is [postcode]"`. The list of offered venues is changed again, because the name slot was encountered. The DAMD database ignores the `pricerange` and `food` slots and so the set of offered venues is now a non-empty subset of the goal venues and whole dialog is matching. However, the model saw the name of the restaurant in the ground-truth context and other problems with state tracking are ignored.

This problem can be emphasized in case of models that use a cumulative state and predict just changes of the state at each turn (e.g., [MinTL](https://github.com/zlinao/MinTL/)). I think that all the informable slots provided by the user should be used in the database calls during evaluation.

The database like this makes of course perfect sense when chatting interactively with a human. But IMHO it overestimates the performance during the evaluation with ground-truth context utterances. Simply because the context might contain a venue name that the system couldn't offer.

**Comment by unbiarirang** [comment]
Thanks for your detailed explanation! I understand what you're talking about.
If we use the ground truth context, it can be problematic.
However, what do you think when using the generated context as input? Do you think it's okay to only use name constraint (if it exists) for database query?

**Comment by Tomiinek** [comment]
Yes, I think it is ok in this case :slightly_smiling_face:
