### ISSUE TITLE
DAMD evaluation

### ISSUE THREAD

**Issue by hpsun1109** [thu-spmi/damd-multiwoz#5]
Hi, thanks for releasing the source code.
However, this log got the much higher result than this paper reported. I don't know the difference between these two settings.
https://github.com/thu-spmi/damd-multiwoz/blob/9b0456d7e590fb5de77ec81e967e8010487eeb56/experiments/all_multi_acts_sample3_sd666_lr0.005_bs80_sp5_dc3/eval_log.json#L89

**Comment by 594zyc** [comment]
Hi, 

The higher result is due to the use of the ground truth belief state for searching the database. The result is comparable to line 7 in Table 2 of our paper (slightly higher since we report the average score of 5 runs in the paper).  If you want to reproduce the result of line 12, you need to set "bspn_mode='bspn'" and "use_true_bspn_for_ctr_eval=False".

**Comment by hpsun1109** [comment]
Thanks for the information.
